Update lint GH Action file

diff --git a/template/.github/workflows/lint-typecheck.yml b/template/.github/workflows/lint-typecheck.yml
--- a/template/.github/workflows/lint-typecheck.yml
+++ b/template/.github/workflows/lint-typecheck.yml
@@ -43,22 +43,23 @@ jobs:
         # Generate JSON report using ESLint. This is used to later show a report inside GitHub UI with warnings and errors (if there are any)
       - name: Run ESLint
         run: npm run lint:js:report
-        continue-on-error: true
 
         # Run Stylelint to check (S)CSS code for errors and warnings
       - name: Run Stylelint
         run: npm run lint:styles
-        continue-on-error: true
+        # Use this instead of continue-on-error to provide proper feedback inside GithubActions while still running the step no matter if previous step failed
+        # continue-on-error shows the step as successfully finished even though it might have errors
+        if: ${{ success() || failure() }}
 
         # Run TypeScript to check if types are valid inside the project
       - name: Run TypeScript type check
         run: npx tsc --noEmit --pretty
-        continue-on-error: true
+        if: ${{ success() || failure() }}
 
         # Show ESLint report generated by one of previous steps
       - name: Show Code Linting Results
         uses: ataylorme/eslint-annotate-action@1.2.0
-        if: always()
+        if: ${{ success() || failure() }}
         with:
           repo-token: "${{ secrets.GITHUB_TOKEN }}"
           report-json: "eslint_report.json"
